# Generated by Django 3.2.9 on 2024-08-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spread', '0002_exchange_exchangeapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinderScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('details', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
